version: '3.2'

services:

#================================================================================================
# POSTGRESQL
#================================================================================================
  postgresql:
    restart: always
    image: dockerframework/postgresql
    ports:
      - "8119:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/postgresql:/var/lib/postgresql              # volume for data
    environment:
      - POSTGRES_VERSION=10.2
      - POSTGRES_ROOT_HOST=postgresql                      # grant user hostmask (optional)
      - POSTGRES_DATABASE=laradock_postgresql              # create database (optional)
      - POSTGRES_USER=laradock                             # grant user name (optional)
      - POSTGRES_PASSWORD=password                         # grant user password (optional)

#================================================================================================
# PGADMIN
#================================================================================================
  pgadmin:
    restart: always
    build:
      context: .
    ports:
      - "8114:80"
    depends_on:
      - postgresql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./session/pgadmin:/sessions                                  # volume for sessions
    environment:
      - PGADMIN_VERSION=3.0
      - PGADMIN_DEFAULT_EMAIL=laradock@laradock.io
      - PGADMIN_DEFAULT_PASSWORD=password
 