version: '3.2'

services:

#================================================================================================
# MONGODB
#================================================================================================
  mongodb:
    restart: always
    build:
      context: .
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_MONGODB}:/etc/mongodb.conf
      - ${DATABASE_MONGODB}/db:/data/db                    # volume for data
      - ${DATABASE_MONGODB}/configdb:/data/configdb        # volume for config
      - ${DATABASE_MONGODB}:/var/lib/mongodb
      - ${LOG_MONGODB}:/var/log/mongodb/mongod.log         # log mongodb
    environment:
      - MONGO_VERSION=${MONGO_VERSION}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_HOST=${MONGO_INITDB_ROOT_HOST}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
