version: '3.2'

services:

#================================================================================================
# POSTGRESQL
#================================================================================================
  postgresql:
    restart: always
    build:
      context: .
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATABASE_POSTGRESQL}:/var/lib/postgresql                   # volume for data
    environment:
      - POSTGRES_VERSION=${POSTGRES_VERSION}
      - POSTGRES_ROOT_HOST=${POSTGRES_ROOT_HOST}                     # grant user hostmask (optional)
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}                       # create database (optional)
      - POSTGRES_USER=${POSTGRES_USER}                               # grant user name (optional)
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}                       # grant user password (optional)
