version: '3.2'

services:

#================================================================================================
# POSTGRESQL
#================================================================================================
  postgresql:
    restart: always
    build:
      context: .
    ports:
      - "8119:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/postgresql:/var/lib/postgresql              # volume for data
    environment:
      - POSTGRES_VERSION=10.2
      - POSTGRES_ROOT_HOST=postgresql                      # grant user hostmask (optional)
      - POSTGRES_DATABASE=laradock_postgresql              # create database (optional)
      - POSTGRES_USER=laradock                             # grant user name (optional)
      - POSTGRES_PASSWORD=password                         # grant user password (optional)
